name: test

on: [push, workflow_dispatch]

jobs:
  test-dotcore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: test
        run: |
          echo $SHELL
          sudo apt update
          sudo apt install -y fish stow
          # exclude pull, apps amd fisher from CI run
          ./bin/dotcore -e "apps|pull|fisher"
          rm ~/.bashrc
          ./start
          . $HOME/.bash_profile
          . $HOME/.bashrc
          ./bin/dotcore-verify
