name: test

on: [push, workflow_dispatch]

jobs:
  test-dotcore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: test
        run: |
          echo $SHELL
          sudo apt-get curl fd-find fish fzf install stow neovim
          rm ~/.bashrc
          rm ~/.bash_profile
          ./start
          . $HOME/.bash_profile
          . $HOME/.bashrc
          ./bin/dotcore-verify
