name: test

on: [push, workflow_dispatch]

jobs:
  test-dotcore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: test
        run: |
          echo $SHELL
          sudo apt update
          sudo apt install -y fish stow
          # exclude apps, fisher and pull from CI test
          ./bin/dotcore -e "apps|fisher|pull"
          rm -f ~/.bashrc
          rm -f ~/.bash_profile
          ./start
          . $HOME/.bash_profile
          . $HOME/.bashrc
          ./bin/dotcore-verify
